### ISSUE TITLE
RCTConekta is undefined

### ISSUE THREAD

**Issue by pabloLarios24** [nuremx/conekta-react-native#1]
![captura de pantalla 2018-09-20 a la s 11 25 55](https://user-images.githubusercontent.com/42230200/45832598-f7667180-bcc7-11e8-8bd3-319d0deb8213.png)

Have this problem, but i don't forget write the line link

**Comment by hecmonn** [comment]
Having the same problem, has this been solved?

**Comment by cesargdm** [comment]
Currently working on this, using the library as a module is not working, but (for now) you can drag the folder to your Xcode project and use it there. PRs are welcome.

**Comment by cesargdm** [comment]
#2

**Comment by cesargdm** [comment]
Solved, please checkup the Notes on iOS at the README
