### ISSUE TITLE
'RCTBridge.h' file not found

### ISSUE THREAD

**Issue by hecmonn** [nuremx/conekta-react-native#2]
Hi

I am getting this error while trying to compile my project on XCode

![image](https://user-images.githubusercontent.com/9221820/47399166-fc6e7480-d6fc-11e8-8b6e-ff8f00d8b421.png)

**Comment by cesargdm** [comment]
Currently working on this, using the library as a module is not working, but (for now) you can drag the folder to your Xcode project and use it there. PRs are welcome.
