### ISSUE TITLE
no such file or directory libRNConekta.a on RELEASE

### ISSUE THREAD

**Issue by cyberdrunk2069** [nuremx/conekta-react-native#3]
I have rebuilt the project several times and when im trying to make a release build of my app i get an error telling that the libRNConekta.a file isnt found, i linked them, but it seems to it doesn't builds or something,
it runs great in dev

**Comment by cesargdm** [comment]
Thank you, we're checking what's happening...

**Comment by cyberdrunk2069** [comment]
![captura de pantalla 2018-11-27 a la s 19 44 25](https://user-images.githubusercontent.com/3833911/49123098-f54b0100-f27c-11e8-9cc3-045fc5574b85.png)
I attached an screenshot of the current error, is literrally a clean ios built project, made the realease config.

**Comment by cesargdm** [comment]
Hey @larve sorry for the delay, we've fixed this error, see a new version in a couple minutes.

**Comment by cesargdm** [comment]
https://github.com/nuremx/conekta-react-native/commit/284459d467ac3bce4772da6951cd23b7d1f818d9
